config/routes.rb
Rails.application.routes.draw do

  root "campsites#index"

  resources :campsites, only: [:index, :show, :new, :create] do
    resources :villagers, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/campsite.rb
class Campsite < ApplicationRecord
  validates :name, presence: true
  validates :owner, presence: true

  has_many :villagers
end

app/models/villager.rb
class Villager < ApplicationRecord
  validates :name, presence: true
  validates :animal, presence: true
  validates :happiness, presence: true, inclusion: { in: 1..10, message: "Happiness must be between 1 - 10" }
  validates :campsite_id, presence: true

  belongs_to :campsite
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/campsites_controller.rb
class CampsitesController < ApplicationController

  def index
    @campsites = Campsite.all
  end

  def show
    @campsite = Campsite.find(params[:id])
    @villagers = @campsite.villagers
  end

  def new
    @campsite = Campsite.new
  end

  def create
    @campsite = Campsite.new(campsite_params)
    if @campsite.save
      flash[:notice] = "Added it yo"
      redirect_to campsites_path
    else
      flash[:alert] = @campsite.errors.full_messages.join(', ')
      render :new
    end
  end

  private

  def campsite_params
    params.require(:campsite).permit(:name, :owner, :description)
  end
end

app/controllers/villagers_controller.rb
class VillagersController < ApplicationController

  def new
    @villager = Villager.new
    @campsite = Campsite.find(params[:campsite_id])
  end

  def create
    @campsite = Campsite.find(params[:campsite_id])
    @villager = Villager.new(villager_params)
    @villager.campsite = @campsite
    if @villager.save
      flash[:notice] = "Added Villager"
      redirect_to @campsite
    else
      flash[:alert] = @villager.errors.full_messages.join(', ')
      render :new
    end
  end

  private

  def villager_params
    params.require(:villager).permit(:name, :animal, :happiness)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/campsites/index.html.erb
<h1>All the Campsites</h1>

<ul>
  <% @campsites.each do |campsite| %>
    <li>
      <%= link_to campsite.name, campsite_path(campsite) %>
    </li>
  <% end %>
</ul>

<%= link_to "Add Campsite", new_campsite_path %>

app/views/campsites/new.html.erb
<h1>Campsite form for new one</h1>

<%= form_for @campsite do |f| %>

<fieldset>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :owner %>
  <%= f.text_field :owner %>

  <%= f.label :description %>
  <%= f.text_field :description %>
</fieldset>

<%= f.submit "Add Campsite" %>
<% end %>

app/views/campsites/show.html.erb
<h1>Name: <%= @campsite.name %></h1>
<h2>Onwer: <%= @campsite.owner %></h2>
<h3>Decription: <%= @campsite.description %></h3>

<ul>
  <% @villagers.each do |villager| %>
    <li>
      <%= villager.name %>
      <%= villager.animal %>
      <%= villager.happiness %>
      <%= villager.created_at.strftime("%B %d %Y") %>
    </li>
  <% end %>
</ul>

<%= link_to "New Villager", new_campsite_villager_path(@campsite) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fantasy Houses</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% flash.each do |key, value| %>
    <p>
      <%= value %>
    </p>
  <% end %>

<%= yield %>

</body>
</html>

app/views/villagers/new.html.erb
<h1>Villagers form for <%=@campsite.name%></h1>

<%= form_for [@campsite, @villager] do |f| %>

<fieldset>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :animal %>
  <%= f.text_field :animal %>

  <%= f.label :happiness %>
  <%= f.number_field :happiness %>
</fieldset>

<%= f.submit "Add Villager" %>
<% end %>